package com.michaelec19.api_character_sheet.model;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * The core entity representing a Dungeons & Dragons 5th Edition character.
 * This model uses Composition to group related data into sub-classes 
 * (BasicInfo, Stats, CombatStats).
 * @author Michaelec19
 * @since 2.0
 */
@Entity
@Table(name = "characters")
public class PlayerCharacter {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Embedded
    private BasicInfo basicInfo;

    @Embedded
    private Stats stats;

    @Embedded
    private CombatStats combatStats;


    public PlayerCharacter() {  
    }

    /**
     * Character Constructor for creating new Sheet characters.
     * The ID is not included as it is automatically generated by the database.
     * through the identity generation strategy.
     */
    public PlayerCharacter(long id, BasicInfo basicInfo, Stats stats, CombatStats combatStats) {
        this.basicInfo = basicInfo;
        this.stats = stats; 
        this.combatStats = combatStats;
    }

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    public BasicInfo getBasicInfo() {
        return basicInfo;
    }
    public void setBasicInfo(BasicInfo basicInfo) {
        this.basicInfo = basicInfo;
    }

    public Stats getStats() {
        return stats;
    }
    public void setStats(Stats stats) {
        this.stats = stats;
    }

    public CombatStats getCombatStats() {
        return combatStats;
    }
    public void setCombatStats(CombatStats combatStats) {
        this.combatStats = combatStats;
    }
}


